version: '3.9'

services:
  flask:
    image: starwars_api
    restart: always
    build:
      context: .
      args:
        INSTALL_LIBS: prod
    environment:
        FLASK_MONGODB_HOST: "mongodb://starwars:starwars@mongo:27017/starwars"
    ports:
      - 5000:5000
    networks:
      - starwars_api
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      # persist mongo db data on volume:
      - mongo_files:/data/db
      # create database, user with roles to access
      - ./.docker/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - starwars_api

  mongo_tests:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing_starwars
    ports:
      - 27018:27017
    networks:
      - starwars_api

  unit_tests:
    image: starwars_api_development
    # scale 0 disables this service to run on `docker-compose up` command to run the
    # unit-tests please execute manually the command: `docker-compose run --rm unit-tests`
    scale: 0
    build:
      context: .
      args:
        INSTALL_LIBS: dev
    environment:
      - FLASK_ENV=testing
    networks:
      - starwars_api
    depends_on:
      - mongo_tests



volumes:
  mongo_files:

networks:
  starwars_api:
    driver: bridge
