[default]
# mongodb settings
MONGODB_HOST = "mongodb://starwars:starwars@127.0.0.1:27017/starwars"

# swagger settings
SWAGGER_UI_DOC_EXPANSION = 'list'
SWAGGER_API_VERSION = "1.0"
SWAGGER_API_TITLE = "StarWars REST API"
SWAGGER_API_DESCRIPTION = "StarWars saga movie data collection"
SWAGGER_API_LICENSE = "Licence: Apache 2.0"
SWAGGER_API_LICENSE_URL = "https://www.apache.org/licenses/LICENSE-2.0"
SWAGGER_API_CONTACT = "Samuel Sampaio"
SWAGGER_API_CONTACT_URL = "https://github.com/samukasmk/starwars_api"
SWAGGER_API_CONTACT_EMAIL = "samuel.maciel.sampaio@gmail.com"

# flask settings
DEBUG = false

# load flask extensions (calling <module>.init_data function)
EXTENSIONS = [
    # structure's extensions
    "starwars_api.extensions.reggie:init_app",
    "starwars_api.extensions.mongodb:init_app",
    "starwars_api.extensions.openapi:init_app",
    # flask rest apis
    "starwars_api.rest_apis.starwars:init_app"
]



[development]
DEBUG = true



[testing]
TESTING = true
MONGODB_PYTEST = "mongodb://root:testing_starwars@127.0.0.1:27018/"
MONGODB_HOST = "mongodb://testing_starwars:testing_starwars@127.0.0.1:27018/testing_starwars"



[production]
