[default]
DEBUG = false

# load flask extensions (calling <module>.init_data function)
EXTENSIONS = [
    # structure's extensions
    "starwars_api.extensions.mongodb:init_app",
    "starwars_api.extensions.openapi:init_app",
    # flask rest apis
    "starwars_api.rest_apis.starwars:init_app"
]



[development]
DEBUG = true



[testing]
MONGOENGINE_HOST = 'mock'


[production]
